In [1]:
import numpy as np
import matplotlib.pyplot as plt
import json
import pandas as pd
import torch
import seaborn as sns
import os
os.environ["KMP_DUPLICATE_LIB_OK"] = "TRUE"

### inspect npz file

In [2]:
npz_file = r"C:\Users\loy49\Desktop\REPO\LSTM_HRC\data_proc_2d\dataset\norm_2026-06-27.npz"
data = np.load(npz_file, allow_pickle=True)

print('keys:', list(data.files))
# print(*(f'{k}: shape={data[k].shape}, dtype={data[k].dtype}, ndim={data[k].ndim}' for k in data.files))
print(len(data.files))

keys: ['velocity_scale_mean', 'velocity_scale_std', 'acceleration_scale_mean', 'acceleration_scale_std', 'velocity_xy_mean', 'velocity_xy_std', 'acceleration_xy_mean', 'acceleration_xy_std', 'pol_vectors_mean', 'pol_vectors_std', 'pol_distance_mean', 'pol_distance_std', 'pol_angles_mean', 'pol_angles_std', 'pol_distance_velocity_mean', 'pol_distance_velocity_std', 'pol_angluer_velocity_mean', 'pol_angluer_velocity_std', 'joint_angles_mean', 'joint_angles_std', 'ratios_mean', 'ratios_std', 'dist_ratios_mean', 'dist_ratios_std']
24


In [3]:
npz_file = r"G:\.shortcut-targets-by-id\1nZZWQUKOdxeC-oo-NKucbuUj38ir4mZC\ITECH_Thesis\Videos\dataset\val\norm\features__cam-04_uid-06_take-02_seg-05_norm.npz"
data = np.load(npz_file, allow_pickle=True)

keys = list(data.files)
for k in keys:
    print(f'{k}: shape={data[k].shape}, dtype={data[k].dtype}, ndim={data[k].ndim}')
# # print(*(f'{k}: shape={data[k].shape}, dtype={data[k].dtype}, ndim={data[k].ndim}' for k in data.files))
# print(len(data.files))

velocity_scale: shape=(1000, 13), dtype=float32, ndim=2
acceleration_scale: shape=(1000, 13), dtype=float32, ndim=2
velocity_xy: shape=(1000, 26), dtype=float32, ndim=2
acceleration_xy: shape=(1000, 26), dtype=float32, ndim=2
pol_vectors: shape=(1000, 26), dtype=float32, ndim=2
pol_distance: shape=(1000, 13), dtype=float32, ndim=2
pol_angles: shape=(1000, 13), dtype=float32, ndim=2
pol_distance_velocity: shape=(1000, 13), dtype=float32, ndim=2
pol_angluer_velocity: shape=(1000, 13), dtype=float32, ndim=2
joint_angles: shape=(1000, 7), dtype=float32, ndim=2
ratios: shape=(1000, 2), dtype=float32, ndim=2
dist_ratios: shape=(1000, 13), dtype=float32, ndim=2
angles_combined: shape=(1000, 20), dtype=float32, ndim=2
step_id: shape=(1000,), dtype=int64, ndim=1
step_id_vector: shape=(1000, 7), dtype=float32, ndim=2
status_id: shape=(1000,), dtype=int64, ndim=1
task_progress: shape=(1000,), dtype=float32, ndim=1


In [4]:
print("progress:", data["task_progress"].max(), data["task_progress"].min(), data["task_progress"].mean())

progress: 0.9931724 0.10252427 0.4982915


### inspect pt file

In [16]:
data_path = r"G:\.shortcut-targets-by-id\1nZZWQUKOdxeC-oo-NKucbuUj38ir4mZC\ITECH_Thesis\Videos\dataset\original\features__cam-04_uid-01_take-01.pt"
#load pt file in py dict
data = torch.load(data_path)
print(data.keys())

data_feat = data['features']
data_label = data['labels']

print(data_feat.keys()) 
print(data_label.keys())


dict_keys(['metadata', 'features', 'labels'])
dict_keys(['velocity_scale', 'acceleration_scale', 'velocity_xy', 'acceleration_xy', 'pol_vectors', 'pol_distance', 'pol_angles', 'pol_distance_velocity', 'pol_angluer_velocity', 'joint_angles', 'ratios', 'dist_ratios'])
dict_keys(['step_id', 'step_id_prob', 'status_id', 'status_id_prob', 'task_progress', 'step_id_plateau', 'step_id_plateau_prob', 'status_id_plateau', 'status_id_plateau_prob', 'step_id_vector', 'status_id_vector', 'step_id_plateau_vector', 'status_id_plateau_vector', 'task_progress_vector'])


In [17]:
#check values:
print(data_label['step_id'].unique())
print(data_label['step_id_vector'].unique())
print(data_label['status_id'].unique())
print(data_label['task_progress'].unique())


tensor([0, 1, 2, 3, 4, 5])
tensor([0.0000e+00, 1.4746e-06, 3.1152e-06,  ..., 1.0000e+00, 1.0000e+00,
        1.0000e+00], dtype=torch.float64)
tensor([0, 1, 2, 3, 4, 5, 6])
tensor([  0.0000,   0.1015,   0.1185,  ...,  99.8342,  99.8755, 100.0000],
       dtype=torch.float64)


In [14]:
data_path = r"G:\.shortcut-targets-by-id\1nZZWQUKOdxeC-oo-NKucbuUj38ir4mZC\ITECH_Thesis\Videos\dataset\segment\features__cam-04_uid-09_take-02_seg-03.pt"
print(data.keys())

data_feat = data['features']
data_label = data['labels']

print(data_feat.keys()) 
print(data_label.keys())

dict_keys(['metadata', 'features', 'labels'])
dict_keys(['velocity_scale', 'acceleration_scale', 'velocity_xy', 'acceleration_xy', 'pol_vectors', 'pol_distance', 'pol_angles', 'pol_distance_velocity', 'pol_angluer_velocity', 'joint_angles', 'ratios', 'dist_ratios'])
dict_keys(['step_id', 'step_id_prob', 'status_id', 'status_id_prob', 'task_progress', 'step_id_plateau', 'step_id_plateau_prob', 'status_id_plateau', 'status_id_plateau_prob', 'step_id_vector', 'status_id_vector', 'step_id_plateau_vector', 'status_id_plateau_vector', 'task_progress_vector'])
